### ISSUE TITLE
Can I overwrite the twig templates?

### ISSUE THREAD

**Issue by chiqui3d** [sadikoff/crud-maker-bundle#11]
I'd like to know if there's any way to overwrite the twig templates without having to modify the bundle you've made.

thanks and great work

**Comment by sadikoff** [comment]
This bundle is extension to maker-bundle, that's why there is no way to modify skeleton templates. This is temporary solution to generate crud, until we get this posibility in maker-bundle.

**Comment by chiqui3d** [comment]
I understand, thank you very much
