### ISSUE TITLE
unimplemented abstract method? - fatal error

### ISSUE THREAD

**Issue by dr-matt-smith** [sadikoff/crud-maker-bundle#13]
/MakeCrud.php on line 29

!!  
!!  Fatal error: Class Koff\Bundle\CrudMakerBundle\Maker\MakeCrud contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Symfony\Bundle\MakerBundle\MakerInterface::generate) in .../testing02_unit/vendor/koff/crud-maker-bundle/src/Maker/MakeCrud.php on line 29
!!  

missing method `generate()` ??

**Comment by sadikoff** [comment]
For now we cannot use crud-maker-bundle with symfony/maker-bundle v1.1 only v1.0 is supported.

I added this limitation to composer.json, if you have version 1.0.7 than this is bug =)

**Comment by dr-matt-smith** [comment]
the problem was solved when I removed koff/crud-maker-bundle, and then removed Symfony's make, and then required off/crud-maker-bundle

- this led to version 1.0 of Symfony's make being added to project

The problem was due to the fact I'd added Symfony make BEFORE added koff/crud-maker-bundle, so I have version 1.1 of Symfony make already added to project

**Comment by dr-matt-smith** [comment]
if works with 1.0 of make that's fine
but should composer give better error message when require fails?
I suppose I would have expected it to tell me I would have to change Symfony make to 1.0, since current 1.1 was incompatible with koff/crud-maker-bundle

message about unimplemented abstract method 'generate()' was very confusing

is this a Composer issue, or can this bundle improve on error message to user when incompatible requirement discovered during require?

**Comment by sadikoff** [comment]
may be on weekend i'll backport some changes from [PR #113](https://github.com/symfony/maker-bundle/pull/113) and everything will work as expected.

**Comment by weaverryan** [comment]
This was my fault :). I made a breaking change in a minor version release. It’s not something I plan to do in the future, as it causes these problems!

**Comment by sadikoff** [comment]
@weaverryan oh it's no problem, I was ready for it

**Comment by sadikoff** [comment]
fixed compatibility  with current version of maker-bundle
