### ISSUE TITLE
Show route hijacks the new route

### ISSUE THREAD

**Issue by komujohn** [sadikoff/crud-maker-bundle#2]
when you generate code for an entity all works well apart from the new route. It seems to be matching that route to the show action. Am thinking this might be solved by moving the new action above the show action. 
According to https://symfony.com/doc/2.6/book/routing.html#book-routing-conditions earlier routes win. Tried it and it worked on 1 controller, don't know if there are bigger considerations. Once again good work.
![make-crud](https://user-images.githubusercontent.com/1990235/35390897-027bb9d0-01ee-11e8-9e1f-6f21ed8d3e60.png)

**Comment by sadikoff** [comment]
Strange, thought I fixed it, will check it later.

**Comment by sadikoff** [comment]
now fixed
