### ISSUE TITLE
sequence wrong in controller methods - /<entity>/new parsed as /<entity>/id for show

### ISSUE THREAD

**Issue by dr-matt-smith** [sadikoff/crud-maker-bundle#3]
the NEW controller method should be BEFORE  the SHOW controller method in the controller template

since 
/<entity>/new 
is parsed by the SHOW method as
/<entity>{id = 'new'}
which then fails with an Object Not found ParamConverter annottion exception

SOLUTION:

locate the new() method BEFORE the show() method in: Controller.tpl.php

I'm new to PUll reuqests for open source stuff - but I'll try to set one one via a fork  :-)

.. matt ..

**Comment by sadikoff** [comment]
thx for the issue, my fault, after creating PR to symfony/maker-bundle I forgot to check everything in my own code =)

**Comment by sadikoff** [comment]
Thx for fast fix.

**Comment by dr-matt-smith** [comment]
you're welcome
- I was looking at the maker bundle, and have a bit more confidence having looked at your code :-)

regards

.. matt ..
